param(
    [string]$ScriptPath = (Join-Path $PSScriptRoot 'InfoNotebook.ps1')
)

$ErrorActionPreference = 'Stop'

function Assert-True {
    param(
        [bool]$Condition,
        [string]$Name
    )
    if (-not $Condition) {
        throw "FAIL: $Name"
    }
}

$scriptText = Get-Content -Path $ScriptPath -Raw
$gradeRulesText = Get-Content -Path (Join-Path $PSScriptRoot 'GradeRules.ps1') -Raw
$serverPrintText = Get-Content -Path (Join-Path $PSScriptRoot 'ServidorImpressao.ps1') -Raw
$workspaceRoot = Split-Path -Parent $PSScriptRoot
$launcherBatText = Get-Content -LiteralPath (Join-Path $workspaceRoot 'InfoNotebook.bat') -Raw
$launcherVbsText = Get-Content -LiteralPath (Join-Path $workspaceRoot 'InfoNotebook.vbs') -Raw

Assert-True ($scriptText -match "\`$form\.Text\s*=\s*'InfoNotebook'") 'titulo nativo evita marca duplicada'
Assert-True ($scriptText -match "\`$splash\.ClientSize\s*=\s*New-Object System\.Drawing\.Size\(520,\s*300\)") 'loading usa composicao compacta'
Assert-True ($scriptText -match "Preparando o InfoNotebook") 'loading comunica a inicializacao com hierarquia clara'
Assert-True ($scriptText -match "\`$splashStatusCard\.BackColor\s*=\s*\[System\.Drawing\.Color\]::FromArgb\(15,\s*18,\s*29\)") 'loading segue a superficie do novo tema'
Assert-True ($scriptText -notmatch 'New-Object System\.Windows\.Forms\.OpenFileDialog') 'loading nao interrompe a abertura para solicitar logo'
Assert-True (([regex]::Matches($scriptText, 'Get-CimInstance Win32_VideoController')).Count -eq 1) 'hardware consulta controladores de video uma unica vez'
Assert-True ($launcherBatText -match 'wscript\.exe\s+//B\s+//Nologo') 'atalho bat delega a inicializacao invisivel'
Assert-True ($launcherBatText -notmatch 'powershell\.exe') 'atalho bat nao abre PowerShell diretamente'
Assert-True ($launcherVbsText -match 'shell\.Run\s+command,\s*0,\s*False') 'launcher executa sem janela de console'
Assert-True ($launcherVbsText -match '-NoProfile\s+-NonInteractive\s+-STA') 'launcher reduz custo e mantem WinForms em STA'
Assert-True ($scriptText -match "Start-Process wscript\.exe\s+-ArgumentList") 'central de testes tambem abre pelo launcher invisivel'
Assert-True ($scriptText -match 'CAIJ_TESTS_OWNER_BOUNDS') 'central de testes recebe a posicao atual do InfoNotebook'
Assert-True ($scriptText -match 'CAIJ_TESTS_OWNER_BOUNDS') 'central de testes recebe a posicao atual do InfoNotebook'
Assert-True ($scriptText.Contains("@{c='T019';n='Notebook Lenovo E14 AMD Ryzen 5 5500';e='1';i=83530047}")) 'catalogo local possui a versao T019 Ryzen 5'
Assert-True ($scriptText.Contains("@{c='T019-';n='Notebook Lenovo E14 i5 10th';e='1';i=83751528}")) 'catalogo local possui a versao T019 i5'
Assert-True ($scriptText.Contains("@{c='T019--';n='Notebook Lenovo E14 i7 10th';e='1';i=83751574}")) 'catalogo local possui a versao T019 i7'
Assert-True ($scriptText -match "\@\{c='T023';n='Notebook Dell Latitude 3420 I7 11th';e='1';i=83020915\}") 'codigo T023 permanece vinculado ao Latitude 3420 i7'
Assert-True ($scriptText -match "\@\{c='T023-';n='Notebook Dell Latitude 3420 I5 11th';e='1';i=84549543\}") 'codigo T023- permanece vinculado ao Latitude 3420 i5'
Assert-True ($scriptText -notmatch "\@\{c='T023';n='Notebook Dell Latitude 3420 I5 11th'") 'catalogo nao troca T023 pelo modelo i5'
Assert-True ($scriptText -notmatch '(?m)^\s*B\s+14\s+238\s+458\s+1\s*$') 'previa com observacao nao deve desenhar separador solto'
Assert-True ($gradeRulesText -match 'GRADE T - TRIAGEM') 'referencia da OS mantem Grade T - Triagem'
Assert-True ($scriptText -match "\@\{L='T'; D='Triagem'\}") 'popup mostra botao Grade T'
Assert-True ($scriptText -match "\@\{L='C'; D='Grade C'\}") 'popup identifica Grade C sem variacao de pintura'
Assert-True ($scriptText -match "if\s*\(\`$letraSel\s*-eq\s*'C'\)[\s\S]*?\`$script:gradeAtual\s*=\s*'C'") 'qualquer equipamento seleciona grade C diretamente'
Assert-True ($scriptText.Contains('$btn.Text = "C`r`nGrade C"')) 'botao identifica a unica classificacao Grade C'
Assert-True ($scriptText -notmatch '&\s*\$script:SelecionarPintura') 'impressao nao abre seletor de variacoes da Grade C'
Assert-True ($gradeRulesText -match "'A'\s+'B'\s+'C'\s+'T - TRIAGEM'\s+'RMA'") 'cadastro oferece uma unica opcao Grade C'
Assert-True ($scriptText -match "\`$tecnicosFixos\s*=\s*@\('Vitor',\s*'Lucas',\s*'Hyrides',\s*'Erick',\s*'Outro'\)") 'cadastro exige identificacao entre tecnicos fixos ou outro'
Assert-True ($scriptText -match '\(\(\$i\s*%\s*2\)\s*\*\s*294\)') 'seletor organiza tecnicos em duas colunas compactas'
Assert-True ($scriptText -match '\$lblSelecaoTecnico\.Location\s*=\s*New-Object System\.Drawing\.Point\(32,\s*344\)') 'status do tecnico fica em faixa propria abaixo das opcoes'
Assert-True ($scriptText -notmatch '\$lblSelecaoTecnico\.Location\s*=\s*New-Object System\.Drawing\.Point\(32,\s*\$\(if') 'selecao nao desfaz a escala DPI do status'
Assert-True ($scriptText -match '\$txtOutroTecnico\.Location\s*=\s*New-Object System\.Drawing\.Point\(32,\s*308\)') 'campo de outro tecnico fica entre as opcoes e o status'
Assert-True ($scriptText -match '\$seletor\.FormBorderStyle\s*=\s*''None''') 'seletor troca a moldura nativa por cabecalho proprio'
Assert-True ($scriptText -match '\$cardTec\.Size\s*=\s*New-Object System\.Drawing\.Size\(208,\s*88\)') 'card lateral destaca o tecnico confirmado'
Assert-True ($scriptText -match '\$osUiMuted\s*=\s*\[System\.Drawing\.Color\]::FromArgb\(166,\s*170,\s*184\)') 'cadastro usa texto auxiliar com maior contraste'
Assert-True ($scriptText -match '\$cadastroHeader\s*=\s*New-Object System\.Windows\.Forms\.Panel') 'cadastro possui cabecalho visual proprio'
Assert-True ($scriptText -match 'Set-RoundedControl\s+-Control\s+\$gCard\s+-Radius\s+6') 'grupos de servicos usam paineis refinados'
Assert-True ($scriptText -notmatch 'RESUMO DO CADASTRO') 'cadastro remove resumo duplicado antes da confirmacao'
Assert-True ($scriptText -match '\$buscaStatus\s*=\s*New-Object System\.Windows\.Forms\.Panel') 'cadastro usa faixa compacta para status da busca'
Assert-True ($scriptText -match '\$servHeader\.Location\s*=\s*New-Object System\.Drawing\.Point\(24,\s*428\)') 'observacao comeca abaixo da busca e dos dados da OS'
Assert-True ($scriptText -match '\$btnCriar\.Location\s*=\s*New-Object System\.Drawing\.Point\(704,\s*636\)') 'acao principal permanece no rodape compacto abaixo da observacao'
Assert-True ($scriptText -match '\$dlg\.ClientSize\s*=\s*New-Object System\.Drawing\.Size\(920,\s*700\)') 'cadastro usa composicao mais ampla e equilibrada'
Assert-True ($scriptText -match '\$dlg\s*\|\s*Add-Member\s+-NotePropertyName\s+CaijTargetWorkingArea') 'cadastro identifica a area util do monitor que exibe o aplicativo'
Assert-True ($scriptText -match '\$maxScaleX\s*=\s*\[Math\]::Max\(0\.72,') 'layout DPI pode reduzir a janela para caber em telas compactas'
Assert-True ($scriptText -match '\$dlg\.StartPosition\s*=\s*\[System\.Windows\.Forms\.FormStartPosition\]::Manual') 'cadastro evita centralizacao que pode deixar a janela fora da tela'
Assert-True ($scriptText -match '\$cadastroOwnerBounds\s*=\s*\$form\.Bounds') 'cadastro usa a posicao atual do InfoNotebook como ancora'
Assert-True ($scriptText -match '\$cadastroX\s*=\s*\[Math\]::Max.*\[Math\]::Min\(\$cadastroXPreferido') 'cadastro sobrepoe a janela principal sem sair da tela'
Assert-True ($scriptText -match '\$btnMinimizarCadastroTopo\.Add_Click') 'cadastro possui controle visivel para minimizar'
Assert-True ($scriptText -match '\$script:osRecentesTimer\.Stop\(\)') 'monitor de OS pausa durante a abertura do cadastro'
Assert-True ($scriptText -match '\$script:cadastroOsAberto\s*=\s*\$true') 'cadastro marca estado modal para evitar interrupcoes'
Assert-True ($scriptText -match 'if\s*\(\$script:cadastroOsAberto\)') 'popup de nova OS nao interrompe o cadastro'
Assert-True ($scriptText -match '\$dlg\.FormBorderStyle\s*=\s*''None''') 'cadastro usa cabecalho proprio sem barra nativa duplicada'
Assert-True ($scriptText -match 'Get-CaijGradeOptions') 'cadastro usa todas as grades'
Assert-True ($scriptText -match 'ContextMenuStrip') 'cadastro abre menu de grades'
Assert-True ($scriptText -match '\$btnGradeOs') 'referencia usa botao de grade'
Assert-True ($scriptText -notmatch '\$txtGradeOs\s*=\s*New-Object System\.Windows\.Forms\.TextBox') 'referencia nao usa texto livre'
Assert-True ($scriptText -match 'class\s+CaijGradeMenuRenderer') 'renderer exclusivo do menu de grades'
Assert-True ($scriptText -match 'tag\s*==\s*"C"') 'renderer identifica a Grade C unica'
Assert-True ($scriptText -match 'Color\.FromArgb\(34,\s*197,\s*94\)') 'renderer usa verde na grade A'
Assert-True ($scriptText -match 'Color\.FromArgb\(245,\s*158,\s*11\)') 'renderer usa ambar na grade B'
Assert-True ($scriptText -match 'Color\.FromArgb\(249,\s*115,\s*22\)') 'renderer usa laranja nas grades C'
Assert-True ($scriptText -match 'Color\.FromArgb\(139,\s*92,\s*246\)') 'renderer usa violeta na grade T'
Assert-True ($scriptText -match 'Color\.FromArgb\(244,\s*63,\s*94\)') 'renderer usa vermelho no RMA'
Assert-True ($scriptText -match 'FillEllipse\(marker,\s*bounds\.Width\s*-\s*12') 'marcador selecionado fica no canto direito'
$rendererSourceMatch = [regex]::Match($scriptText, "(?s)\`$gradeMenuRendererSource\s*=\s*@'\r?\n(?<source>.*?)\r?\n'@")
Assert-True $rendererSourceMatch.Success 'fonte C# do renderer pode ser extraida'
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
Add-Type -TypeDefinition $rendererSourceMatch.Groups['source'].Value -ReferencedAssemblies @('System.Windows.Forms', 'System.Drawing') -WarningAction SilentlyContinue
$rendererInstance = New-Object CaijGradeMenuRenderer
Assert-True ($rendererInstance -is [System.Windows.Forms.ToolStripProfessionalRenderer]) 'renderer C# compila e instancia'
Assert-True ($scriptText -match '\$gradeMenuOs\.ShowImageMargin\s*=\s*\$false') 'menu remove faixa branca de imagens'
Assert-True ($scriptText -match '\$gradeMenuOs\.ShowCheckMargin\s*=\s*\$false') 'menu remove margem nativa de marcacao'
Assert-True ($scriptText -match '\$gradeMenuOs\.Renderer\s*=\s*New-Object CaijGradeMenuRenderer') 'menu usa renderer hibrido'
Assert-True ($scriptText -match '\$gradeMenuOs\.MinimumSize\s*=\s*New-Object System\.Drawing\.Size\(178,\s*0\)') 'menu acompanha largura do card'
Assert-True ($scriptText -match '\$gradeItem\.Size\s*=\s*New-Object System\.Drawing\.Size\(176,\s*30\)') 'itens possuem dimensoes estaveis'
Assert-True ($scriptText -match '\$gradeMenuOs\.Add_Opening') 'menu sincroniza grade selecionada ao abrir'
Assert-True ($scriptText -match '\$item\.Checked\s*=\s*\(\[string\]\$item\.Tag -eq \[string\]\$script:gradeCadastroOs\)') 'marcador representa grade atual'
Assert-True ($scriptText -match 'function\s+Show-CadastroOsConfirm') 'cadastro usa modal moderno de confirmacao'
Assert-True ($scriptText -match 'function\s+Show-CadastroOsResult') 'cadastro usa modal moderno de resultado'
Assert-True ($scriptText -match 'Show-CadastroOsResult\s+`\s*\r?\n\s*-Owner\s+\$dlg') 'resultado substitui caixa padrao do Windows'
Assert-True ($scriptText -match "\`$btnPrint\.Text\s*=\s*'Imprimir etiqueta'") 'resultado oferece impressao imediata'
Assert-True ($scriptText -match "\`$acaoResultado\s*=\s*Show-CadastroOsResult") 'cadastro captura acao escolhida no resultado'
Assert-True ($scriptText -match "\`$script:osImpressaoPendente\s*=\s*\[pscustomobject\]") 'cadastro transporta a OS criada para a impressao'
Assert-True ($scriptText -match "\`$printContext\.OsNumero\s*=\s*\[int\]\`$script:osImpressaoPendente\.osNumero") 'previa usa a OS criada em vez da proxima'
Assert-True ($scriptText -match "os\s*=\s*if\s*\(\`$script:incluirOSAtual\)\s*\{\s*\`$printContext\.OsNumero") 'payload imprime a OS mantida no contexto'
Assert-True ($scriptText -match "-ForcarAltertag:\`$printContext\.CriadaAgora") 'status da impressao volta para a OS criada'
Assert-True ($scriptText -notmatch 'MessageBox\]\:\:Show\(\$msgOk') 'resultado nao usa mensagem padrao de sucesso'
Assert-True ($scriptText -match 'ALTERTAG / NOVA OS') 'modal identifica fluxo Altertag'
foreach ($confirmLabel in @('PRODUTO', 'SERIAL', 'REFERENCIA', 'QUANTIDADE', 'LOCALIZACAO', 'OBSERVACAO')) {
    Assert-True ($scriptText -match [regex]::Escape("'$confirmLabel'")) "modal mostra campo $confirmLabel"
}
Assert-True ($scriptText -match 'Show-CadastroOsConfirm\s+`\s*\r?\n\s*-Owner\s+\$dlg') 'cadastro abre modal moderno'
Assert-True ($scriptText -notmatch "'Confirmar cadastro',\s*\r?\n\s*\[System\.Windows\.Forms\.MessageBoxButtons\]::YesNo") 'cadastro nao usa MessageBox antigo'
Assert-True ($scriptText -match 'Test-CaijGradeRequiresObs') 'validacao de OBS usa regra central'
Assert-True ($scriptText -match "(?s)\`$gradeTxt\s*=.*?'T - TRIAGEM'") 'previa encurta selo da triagem'
Assert-True ($scriptText -match '\$popup\.ClientSize\s*=\s*New-Object System\.Drawing\.Size\(920,\s*628\)') 'popup usa layout horizontal moderno e compacto'
Assert-True ($scriptText -match '\$prevPanel\.Size\s*=\s*New-Object System\.Drawing\.Size\(576,\s*360\)') 'previa preserva proporcao 80x50'
Assert-True ($scriptText -match '\$previewUiSurface\s*=\s*\[System\.Drawing\.Color\]::FromArgb\(15,\s*18,\s*29\)') 'tema da previa usa a mesma superficie da criacao de OS'
Assert-True ($scriptText -match '\$previewUiPrimary\s*=\s*\[System\.Drawing\.Color\]::FromArgb\(94,\s*106,\s*210\)') 'previa usa o mesmo violeta controlado nas acoes principais'
Assert-True ($scriptText -match "\`$form\.FormBorderStyle\s*=\s*'Sizable'") 'janela principal permite redimensionamento'
Assert-True ($scriptText -match '\$form\.MaximizeBox\s*=\s*\$true') 'janela principal habilita o botao maximizar'
Assert-True ($scriptText -match '(?s)\$form\.Add_KeyDown\(.*?Keys\]::F11.*?FormBorderStyle\]::None') 'F11 alterna a janela principal para tela cheia'
Assert-True ($scriptText -match 'assets\\fonts\\Inter-Variable\.ttf') 'tema Windows carrega Inter local'
Assert-True ($scriptText -match 'assets\\fonts\\Orbitron-Variable\.ttf') 'tema Windows carrega Orbitron local'
Assert-True ($scriptText -match 'function\s+Set-CaijWindowsTypography') 'tema aplica tipografia aos popups dinamicos'
Assert-True ($scriptText -match "'Segoe UI Variable Display'") 'titulos usam fonte nativa nitida do Windows'
Assert-True ($scriptText -match "'Segoe UI Variable Text'") 'textos usam fonte nativa nitida do Windows'
Assert-True ($scriptText -match '(?s)\$control\s+-is\s+\[System\.Windows\.Forms\.Button\].*?UseCompatibleTextRendering\s*=\s*\$false') 'botoes usam renderizacao GDI nitida'
Assert-True ($scriptText -match '\$cDim\s*=\s*\[System\.Drawing\.Color\]::FromArgb\(112,\s*117,\s*133\)') 'textos secundarios seguem a hierarquia discreta do cadastro de OS'
Assert-True ($scriptText -match 'SetProcessDpiAwarenessContext') 'aplicativo habilita DPI real do Windows'
Assert-True ($scriptText -match 'function\s+Set-CaijDpiLayout') 'aplicativo possui escala geometrica proporcional'
Assert-True ($scriptText -match '\$Form\.Scale\(\(New-Object System\.Drawing\.SizeF') 'DPI escala controles e dimensoes juntos'
Assert-True ($scriptText -match "\`$form\.Name\s*=\s*'InfoNotebookMain'") 'janela principal identifica layout DPI'
Assert-True ($scriptText -match '\$script:mainLayoutWidth\s*=\s*\$Form\.ClientSize\.Width') 'centralizacao usa largura ja escalada'
Assert-True ($scriptText -match '\$targetScaleX\s*=\s*\[Math\]::Max\(1\.0,\s*\(\[double\]\$this\.ClientSize\.Width') 'tela cheia expande horizontalmente o layout principal'
Assert-True ($scriptText -match '\$targetScaleY\s*=\s*\[Math\]::Max\(1\.0,\s*\(\[double\]\$this\.ClientSize\.Height') 'tela cheia expande verticalmente o layout principal'
Assert-True ($scriptText -match '\$item\.Control\.Scale\(\$scaleFactor\)') 'controles principais acompanham o tamanho da janela'
Assert-True ($scriptText -match '\$script:mainResponsiveScaleX\s*=\s*\$targetScaleX') 'redimensionamento registra escala atual sem acumular saltos'
Assert-True ($scriptText -match "Add-Sec\s+'Processamento e memoria'") 'painel principal organiza processamento e memoria'
Assert-True ($scriptText -match "Add-Row2\s+'Memoria'.*?'Modulos'") 'memoria e modulos usam composicao em duas colunas'
Assert-True ($scriptText -match '\$hairline\.Location\s*=\s*New-Object System\.Drawing\.Point\(250,\s*10\)') 'cabecalhos tecnicos possuem linha de continuidade'
Assert-True ($scriptText -match 'Set-RoundedControl\s+-Control\s+\$barTrack\s+-Radius\s+3') 'barra de bateria usa trilho arredondado'
Assert-True ($scriptText -notmatch "Consultar OS'") 'acao manual de consulta foi removida da barra'
Assert-True ($scriptText -notmatch '\$btnOsAltertag\s*=') 'botao Consultar OS nao e mais criado'
Assert-True ($scriptText -match "Imprimir etiqueta'") 'acao de impressao usa texto simplificado'
Assert-True ($scriptText -match '\$btnTestes\s*=\s*New-Btn[^\r\n]*Testes''[^\r\n]*\$bY1') 'Testes ocupa a linha unica de acoes'
Assert-True ($scriptText -match '\$btnCadastrarOs\s*=\s*New-Btn\s*\(''\+\s+Criar OS''\)[^\r\n]*\$bY1') 'Criar OS ocupa a mesma linha'
Assert-True ($scriptText -match '\$btnImprimir\s*=\s*New-Btn[^\r\n]*Imprimir etiqueta[^\r\n]*\$bY1') 'Imprimir etiqueta ocupa a mesma linha'
Assert-True ($scriptText -match '\$actBarH\s*=\s*50[\s\S]*?\$botY\s*=\s*\$actY\s*\+\s*\$actBarH') 'barra de acoes foi compactada para uma linha'
Assert-True ($scriptText -match '\$cBg\s*=\s*\[System\.Drawing\.Color\]::FromArgb\(7,\s*9,\s*17\)') 'tema principal usa o mesmo canvas da criacao de OS'
Assert-True ($scriptText -match '\$cCard\s*=\s*\[System\.Drawing\.Color\]::FromArgb\(21,\s*24,\s*38\)') 'cartoes principais usam a mesma superficie elevada'
Assert-True ($scriptText -match '\$ttime\.ForeColor\s*=\s*\$cDim') 'data do cabecalho usa texto auxiliar discreto'
Assert-True ($scriptText -match 'INFONOTEBOOK\s+/\s+VISAO GERAL') 'cabecalho principal possui identificacao coerente com o aplicativo'
Assert-True ($scriptText -match '\$script:sectionNumber\+\+') 'secoes tecnicas recebem numeracao visual'
Assert-True ($scriptText -match '\$indexBadge\.Text\s*=\s*\(''\{0:D2\}''\s+-f\s+\$script:sectionNumber\)') 'indice das secoes usa dois digitos'
Assert-True ($scriptText -match '\$keyDivider\.Location\s*=\s*New-Object System\.Drawing\.Point\(144,\s*5\)') 'linhas principais separam rotulo e valor'
Assert-True ($scriptText -notmatch '\$penRail') 'botoes removem trilhos luminosos decorativos'
Assert-True ($scriptText -match 'Add-Sec\s+''Armazenamento e video''\s+\$cAccent') 'secoes principais usam um unico acento violeta'
Assert-True ($scriptText -match '\$cCpuValue\s*=\s*\$cMain') 'processador usa a voz visual principal'
Assert-True ($scriptText -match '\$cRamValue\s*=\s*\$cMain') 'memoria usa a voz visual principal'
Assert-True ($scriptText -match '\$cStorageValue\s*=\s*\$cMain') 'armazenamento usa a voz visual principal'
Assert-True ($scriptText -match '\$cGpuValue\s*=\s*\$cMain') 'placa de video usa a voz visual principal'
Assert-True ($scriptText -match 'Add-Row\s+''Processador''\s+\$info\.CPU\s+\$cCpuValue') 'processador aplica sua cor semantica'
Assert-True ($scriptText -match 'Add-Row2\s+''Memoria''\s+\$info\.RAM\s+\$cRamValue') 'memoria aplica sua cor semantica'
Assert-True ($scriptText -match 'Add-Row\s+''Armazenamento''\s+\$linha\s+\$cStorageValue') 'armazenamento aplica sua cor semantica'
Assert-True ($scriptText -match 'Add-Row\s+''Placa de Video''\s+\$info\.GPU\s+\$cGpuValue') 'placa de video aplica sua cor semantica'
Assert-True ($scriptText -match '(?s)\$btnCadastrarOs\s*=\s*New-Btn.*?FromArgb\(21,\s*24,\s*38\).*?FromArgb\(240,\s*242,\s*248\)') 'cadastro de OS usa botao secundario consistente'
Assert-True ($scriptText -notmatch 'Imprimir Etiqueta via Rede') 'texto antigo da impressao nao retorna apos o envio'
Assert-True ($scriptText -match '\$targetAreaProperty\s*=\s*\$Form\.PSObject\.Properties\[''CaijTargetWorkingArea''\]' -and $scriptText -match '\[System\.Windows\.Forms\.Screen\]::PrimaryScreen\.WorkingArea') 'janelas DPI respeitam a area util do monitor correto com fallback seguro'
Assert-True ($scriptText -match '\$fontRatio\s*=\s*\$scale\s*/\s*\$dpiScale') 'fonte acompanha reducao necessaria para caber na tela'
Assert-True ($scriptText -match 'CaijBaseCornerRadius') 'controles preservam o raio logico original'
Assert-True ($scriptText -match '(?s)Regions do WinForms.*?Set-RoundedControl\s+-Control\s+\$regionControl') 'recortes arredondados sao refeitos depois da escala'
Assert-True ($scriptText -notmatch '(?s)\$btnG\.Add_MouseEnter\(\{.*?\$this\.Location.*?\}\.GetNewClosure\(\)\)') 'hover das grades nao restaura coordenadas anteriores ao DPI'
Assert-True ($scriptText -notmatch '(?s)\$b\.Add_MouseEnter\(\{.*?\$this\.Location.*?\}\.GetNewClosure\(\)\)') 'hover dos botoes principais nao desloca o controle'
Assert-True ($scriptText -match '\$cAccent\s*=\s*\[System\.Drawing\.Color\]::FromArgb\(94,\s*106,\s*210\)') 'tema usa o mesmo violeta controlado da criacao de OS'
Assert-True ($scriptText -match 'CaijWindowTheme.*?UseDarkTitleBar' -and $scriptText -match 'UseDarkTitleBar\(\$form\)') 'barra nativa do Windows acompanha o tema escuro'
Assert-True ($scriptText -notmatch '\$gridPen') 'conteudo principal remove o fundo quadriculado decorativo'
Assert-True ($scriptText -match '\$osCard\.Location\s*=\s*New-Object System\.Drawing\.Point\(20,\s*480\)') 'controle de OS fica abaixo da etiqueta'
Assert-True ($scriptText -match '\$btnAuto\.Location\s*=\s*New-Object System\.Drawing\.Point\(320,\s*508\)') 'fonte dos dados usa faixa inferior equilibrada'
Assert-True ($scriptText -match "caij_modelos_manuais\.json") 'modelos manuais possuem arquivo de historico'
Assert-True ($scriptText -match 'function\s+Add-ModeloManualHistorico') 'historico manual possui gravacao dedicada'
Assert-True ($scriptText -match "caij_ultimo_modelo_manual\.json") 'ultimo modelo manual possui persistencia dedicada por tipo'
Assert-True ($scriptText -match 'function\s+Save-ModeloManualUltimo') 'ultimo modelo manual possui gravacao persistente'
Assert-True ($scriptText -match 'function\s+Get-ModeloManualUltimo') 'formulario consegue restaurar o ultimo modelo'
Assert-True ($scriptText -match '\$modeloSugPanel') 'campo de modelo usa painel proprio de sugestoes'
Assert-True ($scriptText -match 'MODELOS RECENTES') 'painel identifica o historico de modelos'
Assert-True ($scriptText -match 'DrawMode\]::OwnerDrawFixed') 'lista de modelos usa desenho personalizado'
Assert-True ($scriptText -match '\$modeloSugList\.ItemHeight\s*=\s*34') 'lista de modelos ganha altura maior por item'
Assert-True ($scriptText -match '\$alturaLista\s*=\s*\[Math\]::Min\(170,\s*\[Math\]::Max\(68,\s*\(\$quantidadeModelo\s*\*\s*34\)\)\)') 'sugestao de modelo abre com altura minima maior'
Assert-True ($scriptText -match 'StringTrimming\]::EllipsisCharacter') 'sugestao longa usa reticencias sem quebrar o layout'
Assert-True ($scriptText -match '\$modeloLimpo\.Length\s+-gt\s+80') 'historico rejeita entradas concatenadas muito longas'
Assert-True ($scriptText -notmatch 'AutoCompleteMode\]::SuggestAppend') 'campo nao usa popup nativo branco do Windows'
Assert-True ($scriptText -match 'Add-ModeloManualHistorico\s+-Modelo\s+\$modelo') 'modelo manual e salvo ao confirmar dados'
Assert-True ($scriptText -match 'Save-ModeloManualUltimo\s+-Tipo\s+\(\[string\]\$script:tipoEtiqueta\)\s+-Modelo\s+\$modelo') 'modelo confirmado vira o padrao do tipo selecionado'
Assert-True ($scriptText -match '\$modeloManualSalvo\s*=\s*Get-ModeloManualUltimo') 'formulario inicia com o ultimo modelo persistido'

$tokensPersistencia = $null
$errosPersistencia = $null
$astPersistencia = [System.Management.Automation.Language.Parser]::ParseFile(
    $ScriptPath,
    [ref]$tokensPersistencia,
    [ref]$errosPersistencia
)
Assert-True ($errosPersistencia.Count -eq 0) 'script principal pode ser analisado para testar persistencia'
foreach ($nomeFuncao in @('Import-ModelosManuaisUltimos', 'Get-ModeloManualUltimo', 'Save-ModeloManualUltimo')) {
    $funcaoAst = $astPersistencia.Find({
        param($node)
        $node -is [System.Management.Automation.Language.FunctionDefinitionAst] -and
        $node.Name -eq $nomeFuncao
    }, $true)
    Assert-True ($null -ne $funcaoAst) "funcao $nomeFuncao existe para teste funcional"
    Invoke-Expression $funcaoAst.Extent.Text
}

$diretorioTesteModelo = Join-Path ([System.IO.Path]::GetTempPath()) ('caij-modelo-manual-' + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $diretorioTesteModelo | Out-Null
try {
    $script:modeloManualUltimoArquivo = Join-Path $diretorioTesteModelo 'caij_ultimo_modelo_manual.json'
    $script:modelosManuaisUltimos = @{}
    Assert-True (Save-ModeloManualUltimo -Tipo 'Notebook' -Modelo 'Dell Inc. Latitude 3420') 'modelo Dell e gravado sem alterar o texto'
    Assert-True (Save-ModeloManualUltimo -Tipo 'Desktop' -Modelo 'Dell OptiPlex 7090') 'persistencia separa modelos por tipo'

    $script:modelosManuaisUltimos = @{}
    Import-ModelosManuaisUltimos
    Assert-True ((Get-ModeloManualUltimo -Tipo 'Notebook') -ceq 'Dell Inc. Latitude 3420') 'modelo Dell e restaurado exatamente apos recarregar'
    Assert-True ((Get-ModeloManualUltimo -Tipo 'Desktop') -ceq 'Dell OptiPlex 7090') 'modelo de outro tipo permanece independente'
    Assert-True ([string]::IsNullOrWhiteSpace((Get-ModeloManualUltimo -Tipo 'Monitor'))) 'tipo sem modelo nao herda dados de notebook'
}
finally {
    Remove-Item -LiteralPath $diretorioTesteModelo -Recurse -Force
}
Assert-True ($scriptText -match '\$btnAlterarOsPreview') 'previa permite alterar numero da OS'
Assert-True ($scriptText -match '\$btnAlterarOsPreview\.Text\s*=\s*\(Format-OsCodigo') 'previa mostra OS atual no botao'
Assert-True ($scriptText -match "return\s+\('C\{0:D6\}'\s+-f\s+\`$Numero\)") 'Windows formata OS com seis digitos'
Assert-True ($scriptText -match 'function\s+Get-OsAltertagResumoPreview') 'previa possui consulta resumida da OS Altertag'
Assert-True ($scriptText -match '"/os-detalhe\?osNumero=\$OsNumero&produtos=1"') 'consulta da previa solicita produtos da OS'
Assert-True ($scriptText -match '\[switch\]\$ConsultarOnline') 'previa abre sem depender da conferencia online'
Assert-True ($scriptText -match '"/os-detalhe\?osNumero=\$OsNumero&produtos=1".*?-TimeoutSec\s+3\s+-Retries\s+1') 'consulta online da previa usa tentativa curta'
Assert-True ($scriptText -match '\$altertagPreviewTimer\.Interval\s*=\s*150') 'conferencia Altertag roda apos a abertura da previa'
Assert-True ($scriptText -match 'equipamento\s*=\s*Get-ModeloEtiquetaProduto\s+-Descricao\s+\$produtoDescricaoSel\s+-CodigoProduto\s+\$codigoProdutoSel') 'OS criada fornece produto local normalizado durante propagacao'
Assert-True ($scriptText -match '\$altertagCard\.Location\s*=\s*New-Object System\.Drawing\.Point\(628,\s*438\)') 'conferencia Altertag ocupa faixa livre da previa'
foreach ($altertagCampo in @('PRODUTO', 'TECNICO', 'SERIAL')) {
    Assert-True ($scriptText -match [regex]::Escape('"' + $altertagCampo + '  $($altertagResumoPreview.')) "conferencia mostra $altertagCampo"
}
Assert-True ($scriptText -match 'SERIAL DIVERGENTE') 'conferencia destaca divergencia entre etiqueta e Altertag'
Assert-True ($scriptText -match '\$script:AtualizarResumoAltertagPreview\s+-Reconsultar') 'alteracao manual da OS atualiza a conferencia'
Assert-True ($scriptText -match "\`$printContext\.CriadaAgora\)\s*\{\s*\`$script:incluirOSAtual\s*=\s*\`$true") 'impressao direta mantem a OS criada ativa'
Assert-True ($scriptText -match 'function\s+Register-OsNumeroControl') 'controles de OS usam registro central'
Assert-True ($scriptText -match 'function\s+Update-OsNumeroInterface') 'mudanca de OS atualiza toda a interface'
Assert-True ($scriptText -match 'Register-OsNumeroControl\s+-Control\s+\$btnAlterarOsPreview') 'previa acompanha mudanca concorrente de OS'
Assert-True ($scriptText -match 'function\s+Show-OsConcorrenciaPopup') 'criacao concorrente abre alerta global moderno'
Assert-True ($scriptText -match 'Nova OS detectada') 'alerta concorrente possui titulo explicito'
Assert-True ($scriptText -match '(?s)function\s+Show-OsConcorrenciaPopup.*?\$continue\.BackColor\s*=\s*\[System\.Drawing\.Color\]::FromArgb\(94,\s*106,\s*210\)') 'alerta concorrente usa a mesma acao primaria lavanda'
Assert-True ($scriptText -match '(?s)function\s+Show-OsConcorrenciaPopup.*?\$alertForm\.BackColor\s*=\s*\[System\.Drawing\.Color\]::FromArgb\(7,\s*9,\s*17\)') 'alerta concorrente usa o canvas padrao'
Assert-True ($scriptText -match '(?s)function\s+Show-OsConcorrenciaPopup.*?\$headerRail\.Size\s*=\s*New-Object System\.Drawing\.Size\(0,\s*78\)') 'alerta remove trilho decorativo antigo'
Assert-True ($scriptText -match '\$createdCaption\.Text\s*=\s*''OS CRIADA EM OUTRA ESTACAO''') 'alerta explica claramente a origem da OS'
Assert-True ($scriptText -match '\$alertClose\.Add_Click\(\{\s*\$alertForm\.Close\(\)\s*\}\)') 'alerta possui fechamento no cabecalho proprio'
Assert-True ($scriptText -match 'Toda a interface foi atualizada automaticamente') 'alerta explica o avanco automatico'
Assert-True ($scriptText -match "Set-OsNumeroAtual\s+-Numero\s+\`$ProximaOs\s+-Fonte\s+'concorrencia'") 'alerta aplica automaticamente a proxima OS'
Assert-True ($scriptText -match "Invoke-CaijServer\s+-Path\s+'/status-os-local'") 'monitor usa endpoint leve compartilhado'
Assert-True ($scriptText -match "Invoke-CaijServer\s+-Path\s+'/status-os-local'\s+-Method\s+GET\s+-TimeoutSec\s+1\s+-Retries\s+1") 'monitor limita espera para nao travar a interface'
Assert-True ($scriptText -notmatch "(?s)function\s+Update-OsRecentesMonitor.*?catch\s*\{\s*\`$resp\s*=\s*Invoke-CaijServer\s+-Path\s+'/status-os'") 'monitor nao usa fallback externo bloqueante'
Assert-True ($scriptText -match "\`$respRecentes\s*=\s*Invoke-CaijServer\s+-Path\s+'/os-recentes\?limit=15'") 'lista de OS evita carregar produtos de todas as ordens'
Assert-True ($scriptText -notmatch "/os-recentes\?limit=15&produtos=1") 'produto completo fica para o detalhe da OS selecionada'
Assert-True ($scriptText -match "Invoke-CaijServer\s+-Path\s+'/status-os-local'\s+-Method\s+GET\s+-TimeoutSec\s+4\s+-Retries\s+1") 'sincronizacao silenciosa nao bloqueia na API externa'
Assert-True ($scriptText -match '\$script:osRecentesTimer\.Interval\s*=\s*4000') 'criacao concorrente e detectada rapidamente'
Assert-True ($scriptText -match 'function\s+Prompt-OsManual') 'alteracao de OS possui modal dedicado'
Assert-True ($scriptText -match 'Alterar OS da etiqueta') 'modal de OS possui titulo contextual'
Assert-True ($scriptText -match 'Aplicar OS') 'modal de OS possui acao principal clara'
Assert-True ($scriptText -match '(?s)function\s+Prompt-OsManual.*?\$osDialog\.BackColor\s*=\s*\[System\.Drawing\.Color\]::FromArgb\(7,\s*9,\s*17\)') 'modal de OS usa o mesmo canvas da criacao de OS'
Assert-True ($scriptText -match '(?s)function\s+Prompt-OsManual.*?\$osApply\.BackColor\s*=\s*\[System\.Drawing\.Color\]::FromArgb\(94,\s*106,\s*210\)') 'modal de OS usa acao primaria lavanda'
Assert-True ($scriptText -notmatch 'Microsoft\.VisualBasic\.Interaction\]::InputBox') 'alteracao de OS nao usa dialogo nativo antigo'
Assert-True ($scriptText.Contains("@{c='T031';n='Notebook Lenovo T14 i5 10th';e='1';i=83590341}")) 'catalogo local possui T031 i5 com ID'
Assert-True ($scriptText.Contains("@{c='T031-';n='Notebook Lenovo T14 i7 10th';e='1';i=83591236}")) 'catalogo local preserva T031 com traco final'
Assert-True ($scriptText.Contains("@{c='T032-';n='Notebook Lenovo T14 i7 11th';e='1';i=83717625}")) 'catalogo local preserva T032 com traco final'
Assert-True ($scriptText -notmatch "@\{c='P031-?'") 'catalogo local remove codigos antigos P031'
Assert-True ($scriptText -notmatch "@\{c='P032-?'") 'catalogo local remove codigos antigos P032'
Assert-True ($scriptText -match "return\s+@\(\`$codigoFamilia,\s*\(\`$codigoFamilia \+ '-'\),\s*\(\`$codigoFamilia \+ '--'\)\)") 'codigo sem traco consulta automaticamente todas as variantes da familia'
Assert-True ($scriptText -match '\$itensLocais\.Count\s+-gt\s+0\s+-and\s+-not\s+\$buscaFamiliaCodigo') 'busca de familia nao encerra antes de consultar as variantes do servidor'
Assert-True ($scriptText -match '\$produtosBusca\s*\+=\s*@\(\$script:cadastroOsProdutoBuscaLocais\)') 'resultados locais acompanham a busca das variantes como contingencia'
Assert-True ($scriptText -match "Set-ProdutoItems\s+-Items\s+\`$itensLocais\s+-Fonte\s+'catalogo-local'\s+-Mensagem\s+'Atualizando dados online\.\.\.'") 'familia local aparece sem esperar a API'
Assert-True ($scriptText -match "\`$buscaCodigo = \`$termoUpper -match '\^\[A-Z\]\+\\d\+-\*\`$'") 'busca aceita qualquer quantidade de tracos finais'
Assert-True ($scriptText -match "\`$termoUpper\.EndsWith\('-'\)") 'busca reconhece codigo com traco final'
Assert-True ($scriptText -match "\`$codigoAtual -eq \`$termoUpper") 'busca com traco exige codigo exato'
Assert-True ($scriptText -match "\`$codigoAtual\.StartsWith\(\`$termoUpper \+ '-'\)") 'busca sem traco inclui variante final'

foreach ($nomeFuncaoBuscaFamilia in @('Get-ProdutoSortKeyLocal', 'Resolve-ProdutoBuscaTermosLocal', 'Search-CatalogoProdutosLocal')) {
    $funcaoBuscaFamiliaAst = $astPersistencia.Find({
        param($node)
        $node -is [System.Management.Automation.Language.FunctionDefinitionAst] -and
        $node.Name -eq $nomeFuncaoBuscaFamilia
    }, $true)
    Assert-True ($null -ne $funcaoBuscaFamiliaAst) "funcao $nomeFuncaoBuscaFamilia existe para teste da familia de codigos"
    Invoke-Expression $funcaoBuscaFamiliaAst.Extent.Text
}
$script:catalogoProdutosLocal = @(
    @{c='T019';n='Notebook Lenovo E14 AMD Ryzen 5 5500';e='1';i=83530047}
    @{c='T019-';n='Notebook Lenovo E14 i5 10th';e='1';i=83751528}
    @{c='T019--';n='Notebook Lenovo E14 i7 10th';e='1';i=83751574}
    @{c='T023';n='Notebook Dell Latitude 3420 I7 11th';e='1';i=83020915}
)
$termosFamiliaT019 = @(Resolve-ProdutoBuscaTermosLocal -Termo 't019')
Assert-True (($termosFamiliaT019 -join '|') -eq 'T019|T019-|T019--') 'resolucao funcional expande T019 nas tres consultas exatas'
$resultadosFamiliaT019 = @(Search-CatalogoProdutosLocal -Termo 'T019')
Assert-True ($resultadosFamiliaT019.Count -eq 3) 'busca funcional retorna as tres versoes de T019'
Assert-True ((@($resultadosFamiliaT019 | ForEach-Object { [string]$_.codigo }) -join '|') -eq 'T019|T019-|T019--') 'busca funcional mantem cada versao T019 separada e ordenada'
$resultadoExatoT019Traco = @(Search-CatalogoProdutosLocal -Termo 'T019-')
Assert-True ($resultadoExatoT019Traco.Count -eq 1 -and [string]$resultadoExatoT019Traco[0].codigo -eq 'T019-') 'codigo digitado com traco continua sendo uma busca exata'
Assert-True ($scriptText -match "\(Get-ProdutoCodigoLocal \`$_\) -notmatch '\^P'") 'lista de cadastro oculta todos os codigos P'
Assert-True ($scriptText -match "if \(\`$codigoProduto -match '\^P'\) \{ return \`$false \}") 'cadastro impede selecionar codigo P'
Assert-True ($scriptText.Contains("if (`$u -match '^\s*T') { `$score += 20 }")) 'selecao automatica prioriza produtos T'
Assert-True ($scriptText -match '\$impressaoConcluida\s+-and\s+\$script:modoManualEtiqueta') 'impressao manual limpa o contexto apos concluir'
Assert-True ($scriptText -match '\$script:modoManualEtiqueta\s*=\s*\$false') 'impressao manual retorna ao menu principal'
Assert-True ($scriptText -match '\$script:abrirManualNaProximaPrevia\s*=\s*\$false') 'impressao manual nao reabre a previa automaticamente'
Assert-True ($scriptText -notmatch '\$script:reabrindoPreviaManual\s*=\s*\$true') 'impressao manual nao agenda retorno automatico'
Assert-True ($scriptText -notmatch "\`$tipoManualPersistido\s*=\s*if\s*\(\[string\]\`$script:tipoEtiqueta\s+-in\s+@\('Monitor',\s*'Celular'\)\)") 'impressao manual nao preserva estado antigo de tipo'
Assert-True ($scriptText -match "\`$script:modeloEtiqueta\s*=\s*''\s*\r?\n\s*\`$script:serialEtiqueta\s*=\s*''") 'fluxo continuo limpa modelo e serial anteriores'
Assert-True ($scriptText -match "\`$script:obsAtual\s*=\s*''\s*\r?\n\s*\`$script:rnaAtivo\s*=\s*\`$false") 'fluxo continuo limpa observacao e RMA'
Assert-True ($scriptText -match 'function\s+Find-SerialManualNoHistorico') 'modo manual verifica serial no historico'
Assert-True ($scriptText -match 'Serial ja utilizada') 'modo manual alerta serial repetida'
Assert-True ($scriptText -match '\$manualForm\.AcceptButton\s*=\s*\$btnManualSalvar') 'formulario manual suporta confirmacao por teclado'
Assert-True ($scriptText -match '\$manualForm\.FormBorderStyle\s*=\s*''None''') 'formulario manual usa cabecalho proprio igual aos demais modais'
Assert-True ($scriptText -match '\$manualForm\.SelectNextControl') 'Enter avanca entre os campos manuais'
Assert-True ($scriptText -match "\`$btnReimprimir\.Text\s*=\s*'Reimprimir ultima'") 'previa oferece reimpressao segura'
Assert-True ($scriptText -match "\`$script:ultimaEtiquetaPayload\s*=\s*\[string\]\`$dadosJson") 'reimpressao preserva payload exato da etiqueta'
Assert-True ($scriptText -match "Ultima etiqueta reenviada sem alterar a OS") 'reimpressao nao altera contador da OS'
Assert-True ($scriptText -match 'function\s+Show-TecnicoCadastroOs') 'cadastro possui seletor obrigatorio de tecnico'
Assert-True ($scriptText -match '\$btnConfirmarTecnico\.Enabled\s*=\s*\$false') 'seletor inicia sem tecnico padrao confirmado'
Assert-True ($scriptText -match 'Show-CadastroOsAltertagDraft\s+-TecnicoInicial\s+\$tecnicoCadastro') 'cadastro abre somente depois da identificacao'
Assert-True ($scriptText -match "\`$btnTrocarTecnico\.Text\s*=\s*'Trocar'") 'cadastro permite corrigir o tecnico escolhido'
Assert-True ($scriptText -match '-not\s+\$script:osDefinidaManual\)') 'OS manual nao e substituida pela reserva automatica'
Assert-True ($scriptText -match "L\s+'EQUIPAMENTO'\s+120\s+16.*?\`$f2") 'titulo equipamento fica alinhado ao lado do logo'
Assert-True ($scriptText -match 'CaijLogoPreview\s+22\s+20') 'logo CAIJ ancora o inicio do cabecalho na previa'
Assert-True ($scriptText -match 'L\s+\$modeloTop\s+120\s+\$modeloY\s+322') 'modelo forma um bloco visual unico com logo e titulo'
Assert-True ($scriptText -match 'BoxPreview\s+452\s+20\s+618\s+70\s+2') 'grade usa selo compacto independente'
Assert-True ($scriptText -notmatch 'BoxPreview\s+292\s+92\s+404\s+120\s+2') 'grade nao invade mais a caixa da serial'
Assert-True ($scriptText -match '\(NOTEBOOK\|LAPTOP\|COMPUTADOR\|CPU\)') 'previa remove prefixo redundante do modelo'
Assert-True ($scriptText -match "L\s+'SERIAL'\s+22\s+86.*?\`$f2") 'titulo serial usa fonte termica legivel'
Assert-True ($scriptText -match "L\s+'ORDEM DE SERV\.'\s+446\s+86.*?\`$f2") 'titulo da OS usa fonte termica legivel'
Assert-True ($scriptText -match 'B\s+18\s+158\s+604\s+2') 'previa separa cabecalho e conteudo com linha interna recuada'
Assert-True ($scriptText -match '\$alturaDivisoriaInferior\s*=\s*if\s*\(\$temObservacaoEtiqueta\)\s*\{\s*172\s*\}\s*else\s*\{\s*232\s*\}') 'previa libera uma faixa inferior inteira quando existe observacao'
Assert-True ($scriptText -match 'Wrap-TextLines\s+-Text\s+\$obsPreview\s+-MaxLen\s+69\s+-MaxLines\s+3') 'previa comporta observacao limpa em toda a largura'
Assert-True ($scriptText -match 'QrPreview\s+\$qrPreviewPayload\s+398\s+172\s+150') 'previa reduz o QR somente quando precisa abrir espaco para observacao'
Assert-True ($gradeRulesText -notmatch "'C - PINTURA [123]'") 'classificacao nao oferece variacoes de Grade C'
Assert-True ($scriptText -match 'function\s+QrPreview') 'previa possui representacao visual do QR de especificacoes'
Assert-True ($scriptText -match 'function\s+BarcodePreview') 'previa representa o codigo de barras da serial'
Assert-True ($scriptText -match 'BarcodePreview\s+\$serialBar\s+22\s+136') 'codigo de barras aparece abaixo da serial na previa'
Assert-True ($serverPrintText -match 'BARCODE 22,136,`"128`",16,0,0,1,2') 'TSPL imprime Code 128 abaixo da serial'
Assert-True ($serverPrintText -match '\$temObservacaoEtiqueta\s*=\s*\(\$obsLines\.Count\s+-gt\s+0\)') 'TSPL considera observacao somente quando gera linhas'
Assert-True ($serverPrintText -match 'if\s*\(\$temObservacaoEtiqueta\)\s*\{[\s\S]*?\$tspl\s*\+=\s*"BAR 20,334,590,1') 'titulo e faixa OBS ficam dentro da condicao'
Assert-True ($scriptText -match 'QrPreview\s+\$qrPreviewPayload\s+374\s+174\s+198') 'QR ampliado ocupa a metade direita da etiqueta'
Assert-True ($scriptText -notmatch "L\s+'QR DADOS'") 'QR ampliado nao perde espaco com titulo redundante'
Assert-True ($scriptText -match "\`$tituloEspecificacoes\s*=\s*if\s*\(\`$isMonitorEtiqueta\)[\s\S]*?'MONITOR'[\s\S]*?elseif\s*\(\`$isCelularEtiqueta\)[\s\S]*?'CELULAR'") 'previa alterna titulo conforme o equipamento'
Assert-True ($scriptText -match "L\s+'OBS'\s+22\s+346.*?\`$f2") 'observacao usa titulo legivel com respiro abaixo da linha'
Assert-True ($scriptText -match '\$specMaxLen\s*=\s*if\s*\(\$specLabel\s*-eq\s*''GPU''\)\s*\{\s*19\s*\}') 'previa limita GPU ao espaco seguro da fonte normal'
Assert-True ($scriptText -notmatch '\$specLabel\s*-eq\s*''GPU''\s*-and\s*\$specValue\.Length\s*-gt\s*18') 'previa nao reduz mais a fonte da GPU'
Assert-True ($scriptText -match "\@\('TAMANHO',\s*\[string\]\`$script:monitorTamanhoEtiqueta\)") 'previa mostra tamanho do monitor'
Assert-True ($scriptText -match "\@\('ENTRADAS',\s*\[string\]\`$script:monitorEntradasEtiqueta\)") 'previa mostra entradas do monitor'
Assert-True ($scriptText -match "foreach\s*\(\`$entradaNome\s+in\s+@\('VGA',\s*'HDMI',\s*'DISPLAYPORT'\)\)") 'modo monitor possui checklist de entradas'
Assert-True ($scriptText -match "\`$btnTipoMonitor\.Add_Click\(\{\s*&\s*\`$selecionarTipoManual\s+'Monitor'") 'selecao de monitor restaura o modelo persistido do tipo'
Assert-True ($scriptText -match "\`$isMonitorManual\s*=\s*\(\[string\]\`$manualForm\.Tag\s*-eq\s*'Monitor'\)") 'salvamento consulta o tipo persistido no formulario'
Assert-True ($scriptText -match 'function\s+Get-MonitorTamanhoNumero') 'monitor normaliza tamanho numerico'
Assert-True ($scriptText -match 'function\s+Format-MonitorTamanhoEtiqueta') 'monitor adiciona unidade na etiqueta'
Assert-True ($scriptText -match "\`$monitorPolegadas\.Text\s*=\s*'polegadas'") 'campo de monitor mostra polegadas como sufixo fixo'
Assert-True ($scriptText -match 'Format-MonitorTamanhoEtiqueta\s+-Valor\s+\$monitorTamanho') 'salvamento inclui polegadas no tamanho'
Assert-True ($scriptText -match 'function\s+Apply-OsAltertagNaEtiqueta') 'OS selecionada prepara dados da etiqueta'
Assert-True ($scriptText -match '\$script:modeloEtiqueta\s*=\s*\$equipamentoOs') 'produto da OS preenche modelo'
Assert-True ($scriptText -match '\$script:serialEtiqueta\s*=\s*\$serialOs') 'garantia da OS preenche serial'
Assert-True ($scriptText -match "\`$script:abrirManualPorOsSelecionada\s*=\s*\`$true") 'OS de monitor abre conferencia manual'
Assert-True ($scriptText -match 'Apply-OsAltertagNaEtiqueta\s+-Ordem\s+\$sel') 'selecao da tabela aplica seus dados'
Assert-True ($scriptText -match 'tipoEquipamento\s*=\s*if\s*\(\$script:tipoEtiqueta\)') 'payload informa tipo de equipamento'
Assert-True ($scriptText -match 'monitorTamanho\s*=\s*\[string\]\$script:monitorTamanhoEtiqueta') 'payload envia tamanho do monitor'
Assert-True ($scriptText -match 'monitorEntradas\s*=\s*\[string\]\$script:monitorEntradasEtiqueta') 'payload envia entradas do monitor'
Assert-True ($scriptText -notmatch 'monitorResolucaoEtiqueta|monitorResolucao\s*=|RESOL\.') 'modo monitor nao exige resolucao'
Assert-True ($scriptText -match "\`$btnTipoCelular\.Text\s*=\s*'Celular'") 'modo manual oferece tipo Celular'
Assert-True ($scriptText -match "\`$btnTipoCelular\.Add_Click\(\{\s*&\s*\`$selecionarTipoManual\s+'Celular'") 'selecao de celular restaura o modelo persistido do tipo'
Assert-True ($scriptText -match "New-ManualField\s+'IMEI'\s+162") 'celular possui campo IMEI'
Assert-True ($scriptText -notmatch "\`$txtCelularImei\.Add_KeyPress") 'campo IMEI nao bloqueia o teclado fisico'
Assert-True ($scriptText -match "New-ManualField\s+'Bateria'\s+212\s+\`$bateriaCelularInicial") 'celular possui campo bateria'
Assert-True ($scriptText -match "New-ManualField\s+'Armazenamento'\s+262\s+\`$armazenamentoCelularInicial") 'celular possui campo armazenamento'
Assert-True ($scriptText -match "\`$celularImei\s+-and\s+\`$celularImei\.Length\s*-ne\s*15") 'celular valida IMEI com 15 digitos apenas quando informado'
Assert-True ($scriptText -match "@\('IMEI',\s*\[string\]\`$script:celularImeiEtiqueta\)") 'previa mostra IMEI do celular'
Assert-True ($scriptText -match 'celularImei\s*=\s*\[string\]\$script:celularImeiEtiqueta') 'payload envia IMEI do celular'
Assert-True ($scriptText -match '\$gpuPayload\s*=\s*if\s*\(\$script:modoManualEtiqueta\)[\s\S]*?\[string\]\$info\.GPU') 'leitura automatica envia GPU completa para o QR'
Assert-True ($scriptText -match 'gpu\s*=\s*if\s*\(&\s*\$script:IsGpuEtiquetaVisivel\s+\$gpuPayload\)') 'payload usa GPU completa separada da previa curta'
Assert-True ($scriptText -match 'function\s+Format-GpuEtiquetaLocal') 'previa possui formatacao compacta dedicada para GPU'
Assert-True ($scriptText -match '\$specMaxLen\s*=\s*if\s*\(\$specLabel\s*-eq\s*''GPU''\)\s*\{\s*19\s*\}') 'previa preserva modelo e VRAM em abreviacao legivel'
Assert-True ($scriptText -match 'function\s+Test-IsGenericVideoAdapterName') 'leitura possui filtro dedicado para adaptador de video generico'
Assert-True ($scriptText -match '--query-gpu=name,memory\.total') 'NVIDIA usa memoria dedicada informada pelo driver'
Assert-True ($scriptText -match '\$nvidiaGpuMemorias[\s\S]*?\$gpuObj\.AdapterRAM') 'AdapterRAM fica somente como fallback da VRAM NVIDIA'
Assert-True ($scriptText -match 'Adaptador\\s\+de\\s\+V\.deo\\s\+B\.sico') 'filtro reconhece o adaptador basico no Windows em portugues'
Assert-True ($scriptText -match "\`$info\.CPU\s+-match\s+'\(\?i\).*AMD.*Ryzen") 'Ryzen usa Radeon integrada quando somente o driver generico esta disponivel'
Assert-True ($scriptText -match 'function\s+Get-3uToolsDeviceInfo') 'integracao possui leitor local do 3uTools'
Assert-True ($scriptText -match "\`$btnLer3uTools\.Text\s*=\s*'Ler do 3uTools'") 'modo celular oferece leitura do 3uTools'
Assert-True ($scriptText -match "InternationalMobileEquipmentIdentity") 'leitor importa IMEI1 do 3uTools'
Assert-True ($scriptText -match "SerialNumber") 'leitor importa Serial Number do 3uTools'
Assert-True ($scriptText -match "cache\\files\\deviceinfo\.txt") 'leitor usa cache alternativo de IMEI para iPhone nao ativado'
Assert-True ($scriptText -match "serialLinha\s+-eq\s+\`$serial") 'cache alternativo relaciona IMEI ao serial correto'
Assert-True ($scriptText -match "devices_table\\devices_table\.txt") 'leitor resolve nome comercial do iPhone'
Assert-True ($scriptText -match 'function\s+Get-IPhoneBatteryUsb') 'integracao possui leitor USB da bateria'
Assert-True ($scriptText -match 'function\s+Get-IPhoneStorageUsb') 'integracao possui leitor USB do armazenamento'
Assert-True ($scriptText -match 'function\s+Get-AppleDeviceRam') 'integracao resolve RAM pelo identificador exato do aparelho'
Assert-True ($scriptText -match "'iPhone12,1'=4") 'iPhone 11 resolve automaticamente 4GB de RAM'
Assert-True ($scriptText -match 'function\s+Get-AppleStorageFromModelNumber') 'integracao possui fallback de armazenamento pelo codigo do modelo'
Assert-True ($scriptText -match "'MHDH3'='128GB'") 'iPhone MHDH3 resolve automaticamente 128GB de armazenamento'
Assert-True ($scriptText -match '\$storage\s*=\s*Get-AppleStorageFromModelNumber\s+-ModelNumber') 'leitura usa o modelo quando o armazenamento USB nao responde'
Assert-True ($scriptText -match '\$ram\s*=\s*Get-AppleDeviceRam\s+-ProductType\s+\$productType\s+-Armazenamento\s+\$storage') 'leitura combina identificador 3uTools e armazenamento para resolver RAM'
Assert-True ($scriptText -notmatch 'function\s+Confirm-3uToolsTestsStatus') 'triagem celular nao pergunta pelo resultado dos testes 3uTools'
Assert-True ($scriptText -match 'com\.apple\.disk_usage\s+-k\s+TotalDataCapacity') 'armazenamento consulta a capacidade total do iPhone'
Assert-True (Test-Path -LiteralPath (Join-Path $PSScriptRoot 'tools\libimobiledevice\ideviceinfo.exe')) 'binario de leitura do armazenamento acompanha o app'
Assert-True ($scriptText -match "ioregentry\s+AppleSmartBattery") 'leitor consulta diagnostico AppleSmartBattery'
Assert-True ($scriptText -match "NominalChargeCapacity") 'leitor usa capacidade nominal da bateria'
Assert-True ($scriptText -match "DesignCapacity") 'leitor usa capacidade de projeto da bateria'
Assert-True ($scriptText -match "100\.0\s*\*\s*\`$nominal\s*/\s*\`$design") 'saude calcula capacidade nominal sobre projeto'
Assert-True ($scriptText -match "\`$txtCelularBateria\.Text\s*=\s*\[string\]\`$device3u\.Bateria") 'leitura preenche bateria do celular'
Assert-True ($scriptText -match "\`$txtCelularArmazenamento\.Text\s*=\s*\[string\]\`$device3u\.Armazenamento") 'leitura preenche armazenamento do celular'
Assert-True ($scriptText -match "\`$txtRam\.Text\s*=\s*\[string\]\`$device3u\.Ram") 'leitura preserva RAM do celular no modo manual'
Assert-True ($scriptText -match 'RAM:\s*\$\(\[string\]\$device3u\.Ram\)') 'cadastro mostra RAM no resumo da leitura 3uTools'
Assert-True ($scriptText -notmatch '\$device3u\.Testes3uTools|Testes:\s*\$\(\[string\]\$device3u') 'preenchimento nao solicita nem exibe status de testes 3uTools'
Assert-True ($scriptText -match "\`$bateriaCelularInicial\s*=\s*if\s*\(\[string\]\`$script:tipoEtiqueta\s+-eq\s+'Celular'\)") 'celular nao herda bateria do notebook'
Assert-True ($scriptText -match 'elseif\s*\(\$isCelularManual\)[\s\S]*?\$script:memEtiqueta\s*=\s*\$celularArmazenamento') 'salvamento manual preserva armazenamento do celular'
Assert-True ($scriptText -match 'elseif\s*\(\$isCelularManual\)[\s\S]*?\$script:ramEtiqueta\s*=\s*\$ram') 'salvamento manual preserva RAM resolvida do celular'
Assert-True ($scriptText -match "\`$faltamDadosCelular\s*=\s*\`$false") 'celular manual nao exige imei ou bateria'
Assert-True ($scriptText -match "\`$lblServ\.Text\s*=\s*'OBSERVACAO DA OS'") 'cadastro usa observacao como area principal'
Assert-True ($scriptText -match "\`$lblConfigCadastro\.Text\s*=\s*'CONFIGURACOES ATUAIS'") 'cadastro mostra somente o titulo configuracoes atuais'
Assert-True ($scriptText -notmatch 'FIXA NA OBSERVACAO') 'cadastro remove complemento desnecessario do titulo de configuracao'
Assert-True ($scriptText -match "\`$btnEditarConfigCadastro\.Text\s*=\s*'Trocar'") 'cadastro permite trocar a configuracao atual'
Assert-True ($scriptText -match '\$txtObsCadastro\.Add_TextChanged\(\{\s*Update-CadastroOsConfiguracaoPreviewLocal\s*\}\)') 'configuracao permanece visivel enquanto a observacao e digitada'
Assert-True ($scriptText -match 'function\s+Show-CadastroOsConfiguracaoEditorLocal') 'cadastro possui editor dedicado para a configuracao fixa'
Assert-True ($scriptText -match 'function\s+Get-CadastroOsConfiguracaoValoresLocal') 'cadastro usa o hardware coletado quando a etiqueta ainda nao foi aberta'
Assert-True ($scriptText -match "\`$tipoDetectado\s*=\s*if\s*\(\[string\]\`$info\.TipoEquipamento\s+-eq\s+'CPU'\)\s*\{\s*'Desktop'") 'cadastro normaliza CPU detectada como desktop'
Assert-True ($scriptText -match "\`$script:cpuEtiqueta\s*=\s*\`$editoresConfig\['CPU'\]\.Text\.Trim\(\)") 'editor aplica CPU escolhida ao contexto da OS'
Assert-True ($scriptText -match "\`$script:memEtiqueta\s*=\s*\`$editoresConfig\['ARMAZENAMENTO'\]\.Text\.Trim\(\)") 'editor aplica armazenamento escolhido ao contexto da OS'
Assert-True ($scriptText -match "\`$tipoPanel\.Visible\s*=\s*\`$false") 'abas de tipo nao aparecem no cadastro'
Assert-True ($scriptText -match "\`$servPanel\.Visible\s*=\s*\`$false") 'painel de detalhes/servicos nao aparece no cadastro'
Assert-True ($scriptText -match "\`$servicosMarcados\s*=\s*@\(\)") 'cadastro nao envia detalhes como servicos'
Assert-True ($scriptText -match "\`$btnLer3uCadastro\.Text\s*=\s*'Ler informacoes 3uTools'") 'cadastro oferece leitura direta do 3uTools'
Assert-True ($scriptText -notmatch "\`$btnSelecionarServicos\.Text\s*=\s*'Selecionar detalhes'") 'checklist de detalhes foi removido da tela'
Assert-True ($scriptText -match 'function\s+New-CadastroOsObservacaoLocal') 'cadastro monta observacao final antes do envio'
Assert-True ($scriptText -match "return \('CONFIG: ' \+ \(\`$itensConfig -join ' \| '\)\)") 'cadastro inclui linha CONFIG compacta na observacao'
Assert-True ($scriptText -match 'Get-CadastroOsConfiguracaoAtualLocal\s+-TipoEquipamento\s+\$TipoEquipamento') 'configuracao da observacao respeita o tipo cadastrado'
Assert-True ($scriptText -match 'Format-CadastroOsCpuConfigLocal\s+-Cpu') 'linha CONFIG resume o processador'
Assert-True ($scriptText -match 'Format-CadastroOsArmazenamentoConfigLocal\s+-Armazenamento') 'linha CONFIG resume o armazenamento'
Assert-True ($scriptText -match 'Format-CadastroOsRamConfigLocal\s+-Ram') 'linha CONFIG resume a memoria RAM'
Assert-True ($scriptText -match 'Format-CadastroOsGpuConfigLocal\s+-Gpu') 'linha CONFIG resume a placa de video detectada'
Assert-True ($scriptText -match '\(\?:CONFIG\|Configuracao atual\)\\s\*:\s*') 'cadastro evita duplicar CONFIG e reconhece o formato anterior'
Assert-True ($scriptText -match '\$origemCelular\s*=\s*\$DadosCelular[\s\S]*?\$script:tipoEtiqueta\s+-eq\s+''Celular''') 'celular usa o 3uTools ou estado celular sem herdar o notebook'
Assert-True ($scriptText -match 'return \(\$itensDispositivo -join '' - ''\)') 'celular usa uma unica linha compacta sem status de testes'
Assert-True ($scriptText -match "@\('Ram',\s*\[string\]\`$origemCelular\.Ram\)") 'linha de testes inclui RAM resolvida'
Assert-True ($scriptText -match "@\('Ciclos',.*\`$origemCelular\.Ciclos") 'linha de testes inclui ciclos quando disponiveis'
Assert-True ($scriptText -notmatch 'TESTES 3UTOOLS:|DISPOSITIVO:') 'formato antigo foi removido da observacao'
Assert-True ($scriptText -match "if \(\`$tipoAtualCadastro -eq 'Monitor'\) \{ return '' \}") 'monitor permanece sem configuracao automatica'
foreach ($nomeFuncaoConfig in @(
    'Format-CadastroOsCpuConfigLocal',
    'Format-CadastroOsArmazenamentoConfigLocal',
    'Format-CadastroOsRamConfigLocal',
    'Format-CadastroOsGpuConfigLocal',
    'Get-CadastroOsConfiguracaoValoresLocal',
    'Get-CadastroOsConfiguracaoAtualLocal',
    'Format-TecnicoCadastroObservacaoLocal',
    'Get-CadastroOsDiaPrefixoLocal',
    'New-CadastroOsObservacaoLocal'
)) {
    $funcaoConfigAst = $astPersistencia.Find({
        param($node)
        $node -is [System.Management.Automation.Language.FunctionDefinitionAst] -and
        $node.Name -eq $nomeFuncaoConfig
    }, $true)
    Assert-True ($null -ne $funcaoConfigAst) "funcao $nomeFuncaoConfig existe para testar CONFIG"
    Invoke-Expression $funcaoConfigAst.Extent.Text
}
foreach ($nomeFuncaoApple in @('Get-AppleDeviceRam', 'Get-AppleStorageFromModelNumber')) {
    $funcaoAppleAst = $astPersistencia.Find({
        param($node)
        $node -is [System.Management.Automation.Language.FunctionDefinitionAst] -and
        $node.Name -eq $nomeFuncaoApple
    }, $true)
    Assert-True ($null -ne $funcaoAppleAst) "funcao $nomeFuncaoApple existe para testar dados Apple"
    Invoke-Expression $funcaoAppleAst.Extent.Text
}
Assert-True ((Get-AppleDeviceRam -ProductType 'iPhone12,1' -Armazenamento '128GB') -eq '4GB') 'RAM funcional do iPhone 11 resulta em 4GB'
Assert-True ((Get-AppleStorageFromModelNumber -ModelNumber 'MHDH3 BR/A') -eq '128GB') 'armazenamento funcional do MHDH3 resulta em 128GB'
$info = [pscustomobject]@{
    TipoEquipamento = 'CPU'
    CPU = 'Intel Core i5 10'
    RAM = '16GB DDR4'
    Discos = "512GB SSD - NVMe`r`n1000GB HDD - SATA"
    GPU = 'Intel UHD Graphics'
}
$servicosCadastroEstado = [pscustomobject]@{ ConfiguracaoEditada = $false }
$script:tipoEtiqueta = ''
$script:cpuEtiqueta = ''
$script:ramEtiqueta = ''
$script:memEtiqueta = ''
$script:gpuEtiqueta = ''
$configDetectadaTeste = Get-CadastroOsConfiguracaoAtualLocal -TipoEquipamento 'Desktop'
Assert-True ($configDetectadaTeste -eq 'CONFIG: I5 10TH | 512GB SSD | 16GB RAM | INTEL UHD') 'cadastro usa configuracao coletada e resumida antes de abrir a previa'
$script:tipoEtiqueta = 'Notebook'
$script:cpuEtiqueta = 'Intel(R) Core(TM) i7-1165G7'
$script:ramEtiqueta = '16GB DDR4'
$script:memEtiqueta = 'SSD 512GB'
$script:gpuEtiqueta = 'NVIDIA RTX 3050 4GB'
$script:bateriaEtiqueta = '88%'
$configTeste = Get-CadastroOsConfiguracaoAtualLocal -TipoEquipamento 'Notebook'
Assert-True ($configTeste -eq 'CONFIG: I7 11TH | 512GB SSD | 16GB RAM | RTX 3050 4GB') 'CONFIG funcional inclui os dados resumidos em ordem legivel'
Assert-True ((Format-CadastroOsArmazenamentoConfigLocal -Armazenamento '476GB NVMe - Samsung') -eq '476GB SSD') 'armazenamento NVMe aparece resumido como SSD'
Assert-True ((Format-CadastroOsRamConfigLocal -Ram '16GB DDR4 3200 MHz') -eq '16GB RAM') 'memoria aparece resumida como RAM'
$observacaoConfigTeste = New-CadastroOsObservacaoLocal -Observacao "Inspecao inicial`r`n$configTeste" -Tecnico 'Vitor' -TipoEquipamento 'Notebook'
Assert-True (([regex]::Matches($observacaoConfigTeste, '(?im)^CONFIG:')).Count -eq 1) 'observacao funcional nao duplica a linha CONFIG'
$dadosCelularTeste = [pscustomobject]@{ Imei='359999999999999'; Armazenamento='256GB'; Ram='4GB'; Bateria='87%'; Ciclos=321 }
$dispositivoTeste = Get-CadastroOsConfiguracaoAtualLocal -TipoEquipamento 'Celular' -DadosCelular $dadosCelularTeste
Assert-True ($dispositivoTeste -eq 'Imei: 359999999999999 - Ram: 4GB - Bateria: 87% - Ciclos: 321') 'linha funcional omite o resultado dos testes 3uTools'
$observacaoDispositivoTeste = New-CadastroOsObservacaoLocal -Observacao "Inspecao celular`r`n$dispositivoTeste" -Tecnico 'Vitor' -TipoEquipamento 'Celular' -DadosCelular $dadosCelularTeste
Assert-True (([regex]::Matches($observacaoDispositivoTeste, '(?im)Imei:')).Count -eq 1) 'observacao funcional nao duplica a linha de dados do celular'
Assert-True ((Get-CadastroOsConfiguracaoAtualLocal -TipoEquipamento 'Monitor') -eq '') 'monitor funcional nao recebe dados automaticos'
Assert-True ($scriptText -match "ToString\('dd/MM/yy'\)[\s\S]*?ToString\('HH:mm'\)") 'observacao usa data e horario no prefixo'
Assert-True ($scriptText -match 'function\s+Format-CadastroOsCpuConfigLocal') 'cadastro normaliza CPU na configuracao atual'
Assert-True ((Format-CadastroOsCpuConfigLocal -Cpu 'Intel Core i5 10210U') -eq 'I5 10TH') 'configuracao atual resume modelo Intel pela geracao'
Assert-True ($scriptText -match '\$observacaoCadastroFinal\s*=\s*New-CadastroOsObservacaoLocal[^\r\n]*-TipoEquipamento\s+\$tipoCadastroInferido[^\r\n]*-DadosCelular\s+\$estadoServicosAtual\.DadosCelular') 'envio usa observacao padronizada e os dados do aparelho atual'
Assert-True ($scriptText -notmatch '\$txtObsCadastro\.Text\s*=\s*if\s*\(\$obsAtual\)') '3uTools nao duplica seus dados no texto livre da observacao'
Assert-True ($scriptText -notmatch '\$script:cadastroOsServicosSelecionados\[') 'eventos nao indexam estado global de servicos'
Assert-True ($scriptText -match '\$servicosCadastroEstado\.DadosCelular\s*=\s*\$device3u') 'cadastro preserva os dados lidos do 3uTools'
Assert-True ($scriptText -match 'etiqueta\s*=\s*\$etiquetaCadastro') 'OS criada transporta os dados do celular para a impressao'
Assert-True ($scriptText -match 'observacao\s*=\s*\$observacaoCadastroFinal') 'OS criada transporta a mesma observacao para a impressao'
Assert-True ($scriptText -match 'function\s+Invoke-CaijUiResponsiveJsonPost') 'criacao da OS possui chamada de rede responsiva'
Assert-True ($scriptText -match 'UploadStringTaskAsync') 'criacao da OS executa o POST fora da interface principal'
Assert-True ($scriptText -match 'Application\]::DoEvents\(\)[\s\S]*?Start-Sleep\s+-Milliseconds\s+40') 'interface continua processando eventos enquanto aguarda o AlterTag'
Assert-True ($scriptText -match 'Invoke-CaijUiResponsiveJsonPost[\s\S]*?/criar-os-altertag') 'botao Criar OS usa a chamada responsiva'
Assert-True ($scriptText -match '\$popup\.ShowDialog\(\$form\)') 'previa de impressao sobrepoe a janela principal'
Assert-True ($scriptText -match '\$popMinimize\.Add_Click') 'previa de impressao possui controle visivel para minimizar'
Assert-True ($scriptText -match '\$popup\.ShowDialog\(\$form\)') 'previa de impressao sobrepoe a janela principal'
Assert-True ($scriptText -match '\$popMinimize\.Add_Click') 'previa de impressao possui controle visivel para minimizar'
Assert-True ($scriptText -match '\$popup\.TopMost\s*=\s*\$false') 'previa nao fica presa acima de todos os programas'
Assert-True ($scriptText -match '\$printContext\.Etiqueta\s*=\s*\$script:osImpressaoPendente\.etiqueta') 'impressao recebe o contexto da etiqueta recem-cadastrada'
Assert-True ($scriptText -match '\$printContext\.Observacao\s*=\s*\[string\]\$script:osImpressaoPendente\.observacao') 'impressao recebe a observacao confirmada na OS'
Assert-True ($scriptText -match '\$script:obsAtual\s*=\s*\$printContext\.Observacao\.Trim\(\)') 'previa reaplica a observacao da OS sem nova digitacao'
Assert-True ($scriptText -match 'Wrap-TextLines\s+-Text\s+\$obsPreview\s+-MaxLen\s+69\s+-MaxLines\s+3') 'previa reserva tres linhas largas para a observacao da OS'
Assert-True ($scriptText -match 'function\s+Apply-CadastroOsEtiquetaNaImpressao') 'impressao possui aplicador dedicado para dados do cadastro'
Assert-True ($scriptText -match '\$script:celularImeiEtiqueta\s*=\s*\[string\]\$Etiqueta\.imei') 'contexto cadastrado substitui o IMEI da etiqueta'
Assert-True ($scriptText -match '\$script:bateriaEtiqueta\s*=\s*\[string\]\$Etiqueta\.bateria') 'contexto cadastrado substitui a bateria da etiqueta'
Assert-True ($scriptText -match '\$script:memEtiqueta\s*=\s*\[string\]\$Etiqueta\.armazenamento') 'contexto cadastrado substitui o armazenamento da etiqueta'
Assert-True ($scriptText -match 'Apply-CadastroOsEtiquetaNaImpressao\s+-Etiqueta\s+\$printContext\.Etiqueta') 'dados do celular sao reaplicados depois dos dados da OS'
Assert-True ($scriptText -match 'function\s+Test-DesktopProduto') 'cadastro reconhece desktop pela descricao do produto'
Assert-True ($scriptText -match 'function\s+Get-ModeloEtiquetaProduto') 'modelo da etiqueta possui normalizador dedicado'
Assert-True ($scriptText -match 'function\s+Test-CelularProduto') 'classificacao de celular possui detector dedicado'
Assert-True ($scriptText -match "Test-CelularProduto\s+-Descricao\s+\`$equipamentoOs[\s\S]*?\`$script:tipoEtiqueta\s*=\s*'Celular'") 'OS de celular selecionada limpa e troca o contexto de notebook'
Assert-True ($scriptText -match "\(\?:SMARTPHONE\|CELULAR\|TELEFONE\|TABLET\)") 'modelo remove a categoria comercial antes do nome do celular'
Assert-True ($scriptText -match "if\s*\(\`$tipoCadastroInferido\s*-eq\s*'Celular'\)\s*\{\s*\`$dadosCelularCadastro") 'OS de celular cria contexto de impressao mesmo sem leitura 3uTools'
Assert-True ($scriptText -match '\$modeloCelularCadastro\s*=\s*if[\s\S]*?Get-ModeloEtiquetaProduto\s+-Descricao\s+\$produtoDescricaoSel') 'OS de celular usa o produto selecionado como modelo alternativo'
Assert-True ($scriptText -match "\`$script:tipoEtiqueta\s*=\s*'Celular'[\s\S]*?\`$script:cpuEtiqueta\s*=\s*''[\s\S]*?\`$script:ramEtiqueta\s*=\s*''[\s\S]*?\`$script:gpuEtiqueta\s*=\s*''") 'contexto celular limpa dados residuais do notebook'
Assert-True ($scriptText -match '\(\?:CPU\|DESKTOP\|MINI\\s\+DESKTOP\|COMPUTADOR\\s\+DESKTOP\)') 'normalizador remove codigo T somente de produtos desktop'
Assert-True ($scriptText -match "elseif\s*\(Test-DesktopProduto\s+-Descricao\s+\`$produtoDescricaoSel\)\s*\{\s*'Desktop'") 'cadastro infere desktop a partir do produto selecionado'
Assert-True ($scriptText -match "tipoEquipamento\s*=\s*'Desktop'[\s\S]*?produtoCodigo\s*=\s*\`$codigoProdutoSel") 'OS criada transporta contexto desktop isolado para impressao'
Assert-True ($scriptText -match "if\s*\(\`$tipoCadastro\s+-eq\s*'Desktop'\)[\s\S]*?\`$script:bateriaEtiqueta\s*=\s*\`$null") 'contexto desktop remove bateria e dados do computador local'
Assert-True ($scriptText -match "\`$btnTipoDesktop\.Text\s*=\s*'Desktop'") 'modo manual oferece tipo Desktop'
Assert-True ($scriptText -match "\`$btnTipoDesktop\.Add_Click\(\{\s*&\s*\`$selecionarTipoManual\s+'Desktop'") 'selecao de desktop restaura o modelo persistido do tipo'
Assert-True ($scriptText -match "\`$isDesktopEtiqueta\s*=\s*\(\[string\]\`$script:tipoEtiqueta\s+-eq\s*'Desktop'\)") 'previa reconhece contexto Desktop'
Assert-True ($scriptText -match "elseif\s*\(\`$isDesktopEtiqueta\)\s*\{\s*'DESKTOP'") 'previa identifica a secao Desktop'
Assert-True ($scriptText -match 'observacao\s*=\s*\$observacaoCadastroFinal') 'cadastro envia observacao padronizada ao servidor'
Assert-True ($scriptText -match '\$serialPreviewFont\s*=\s*if\s*\(\$serialTop\.Length\s+-le\s+22\)\s*\{\s*\$f3') 'previa reserva altura para o codigo de barras sem sobrepor a serial'
Assert-True ($scriptText -match '\$bateriaCelularPreview\s*=\s*"\$\(\[math\]::Min[\s\S]*?%"') 'previa de celular mostra somente percentual da bateria'
Assert-True ($scriptText -match "@\('ARMAZ\.',\s*\[string\]\`$script:memEtiqueta\)") 'previa de celular mostra armazenamento'
Assert-True ($scriptText -notmatch '\$celularSemObsPreview') 'celular preserva a metade direita para o QR'
Assert-True ($scriptText -match '\$valueX\s*=\s*if\s*\(\$isCelularEtiqueta') 'dados do celular permanecem na coluna esquerda'
Assert-True ($scriptText -match 'if\s*\(\$obsLines\.Count\s+-gt\s+0\)') 'previa oculta faixa OBS quando estiver vazia'
Assert-True ($scriptText -notmatch "\`$isCelularEtiqueta\s+-and\s+\`$specLabel\s+-eq\s+'BATERIA'[\s\S]*?\`$f4") 'previa mantem IMEI e bateria na mesma escala'
Assert-True ($scriptText -match 'function\s+Set-AppStatus\s*\{[\s\S]*?\$Cor\s*\r?\n[\s\S]*?\$Cor\s+-isnot\s+\[System\.Drawing\.Color\]') 'status aceita cor ausente no alerta de nova OS'
Assert-True ($scriptText -match '\$controlDeck\.SendToBack\(\)\s*\r?\n\s*foreach\s*\(\$previewControl') 'painel direito fica atras dos controles'
Assert-True ($scriptText -notmatch 'BoxPreview\s+10\s+10\s+630\s+390\s+2|BoxPreview\s+2\s+4\s+638\s+398') 'previa remove moldura externa sensivel a inclinacao do rolo'
Assert-True ($scriptText -match "System\.Drawing\.Font\('Segoe UI Semibold'") 'previa usa tipografia mais limpa na hierarquia principal'
Assert-True ($scriptText -match '\$previewControl\.BringToFront\(\)') 'controles da previa voltam para frente'
Assert-True ($scriptText -match '\$resp\.produtoErro') 'interface informa pendencia ao adicionar produto'

$serverPath = Join-Path $PSScriptRoot 'ServidorImpressao.ps1'
$serverText = Get-Content -Path $serverPath -Raw
Assert-True ($serverText -match "'ERICK'") 'servidor permite tecnico Erick'
Assert-True ($serverText -match "'FELIPE'") 'servidor permite tecnico Felipe'
Assert-True ($serverText -match 'function\s+Test-TecnicoCadastroValido') 'servidor aceita tecnico informado pela opcao Outro'
Assert-True ($serverText -match "\`$rota\s+-eq\s+'/status-os-local'") 'servidor expoe estado leve para todas as estacoes'
Assert-True ($serverText -match '\$script:vhsysProdutosBuscaCacheTtlSec\s*=\s*300') 'servidor reutiliza buscas recentes de produtos'
Assert-True ($serverText -match "\`$isCodigo\s*=.*?'\^\(\?:T\\d\{3,") 'busca por codigo operacional evita consulta redundante por descricao'
Assert-True ($serverText -match '\$script:vhsysOrdensRecentesCacheTtlSec\s*=\s*8') 'servidor reutiliza lista recente entre estacoes'
Assert-True ($serverText -match '\$ultimoEfetivo\s*=\s*\[Math\]::Max\(\$ultimoAtual,\s*\$UltimoConfirmado\)') 'estado concorrente nunca regride para OS antiga'
Assert-True ($serverText -match 'proximoDisponivel=\[int\]\$estadoAposCriacao\.proximoDisponivel') 'criacao retorna a proxima OS compartilhada'
Assert-True ($serverText -match 'T - TRIAGEM') 'servidor reconhece Grade T - Triagem'
Assert-True ($serverText -match "\`$gradeBadge\s*=\s*'T - TRIAGEM'") 'impressao encurta selo da triagem'
Assert-True ($serverText.Contains("if (`$codigo -match '^T') { return '0_' + `$codigo }")) 'servidor ordena produtos T primeiro'
Assert-True ($serverText.Contains("`$codPref -match '^[TPA]'")) 'servidor preserva produtos T entre os preferenciais'
Assert-True ($serverText -match '\$isMonitor\s*=\s*\(\$tipoEquipamento\s+-match') 'servidor reconhece etiqueta de monitor'
Assert-True ($serverText -match '\$isCelular\s*=\s*\(\$tipoEquipamento\s+-match') 'servidor reconhece etiqueta de celular'
Assert-True ($serverText -match '\$isDesktop\s*=\s*\(\$tipoEquipamento\s+-match') 'servidor reconhece etiqueta de desktop'
Assert-True ($serverText -match 'TEXT 22,173,.*MONITOR') 'TSPL identifica configuracao de monitor'
foreach ($monitorLabel in @('TAMANHO', 'ENTRADAS')) {
    Assert-True ($serverText -match [regex]::Escape("'$monitorLabel'")) "TSPL inclui campo $monitorLabel"
}
Assert-True ($serverText -notmatch 'monitorResolucao|RESOL\.') 'TSPL de monitor nao imprime resolucao'
Assert-True ($serverText -match 'TEXT 22,173,.*CELULAR') 'TSPL identifica configuracao de celular'
Assert-True ($serverText -match "@\('IMEI',\s*\`$imeiInfo\)") 'TSPL de celular inclui IMEI'
Assert-True ($serverText -match "@\('BATERIA',\s*\`$batInfo\)") 'TSPL de celular inclui bateria'
Assert-True ($serverText -match "@\('ARMAZ\.',\s*\`$storageInfo\)") 'TSPL de celular inclui armazenamento'
Assert-True ($serverText -match "@\('ARMAZENAMENTO',\s*\`$ficha\.disco\)") 'ficha QR de celular inclui armazenamento'
Assert-True ($serverText -match 'elseif\s*\(\$isDesktop\)\s*\{[\s\S]*?TEXT 22,173,.*DESKTOP') 'TSPL possui layout exclusivo para desktop'
Assert-True ($serverText -match '\$mostrarBateria\s*=\s*\(-not\s+\$isDesktop') 'servidor nunca inclui bateria em desktop'
Assert-True ($serverText -match 'function\s+Format-GpuEtiqueta') 'TSPL possui formatacao compacta dedicada para GPU'
Assert-True ($serverText -match '\$gpu\s*=\s*if\s*\(\$modoManual\)\s*\{\s*\$gpuCompleta\s*\}') 'impressao preserva o valor manual da GPU'
Assert-True ($serverText -match 'QUADRO\\s\+RTX[\s\S]*?\$vramSuf') 'abreviacao automatica preserva VRAM da Quadro RTX'
Assert-True ($serverText -match '\$gpuFont\s*=\s*''2''') 'GPU usa fonte normal depois de abreviar modelo e VRAM'
Assert-True ($serverText -match "\`$qrTipo\s*=\s*if[\s\S]*?elseif\s*\(\`$isDesktop\)\s*\{\s*'DESKTOP'") 'ficha QR identifica desktop corretamente'
Assert-True ($serverText -match 'function\s+Short-ModeloEtiqueta') 'servidor resume o modelo impresso sem alterar o QR'
Assert-True ($serverText -match 'function\s+Save-QrFicha') 'servidor salva os dados completos vinculados ao QR'
Assert-True ($serverText -match 'function\s+Publish-QrFicha') 'servidor tenta publicar a ficha no dominio publico'
Assert-True ($serverText -match 'https://infocaij\.com\.br') 'servidor usa o dominio publico da CAIJ'
Assert-True ($serverText -match '\$qrPayload\s*=\s*\$publicQrUrl') 'QR usa somente o dominio publico validado'
Assert-True ($serverText -match 'function\s+Get-QrFichaPage') 'servidor gera ficha visual para leitura no celular'
Assert-True ($serverText -match 'function\s+ConvertTo-HtmlSafe') 'ficha usa funcao de escape HTML sem colidir com alias do PowerShell'
Assert-True ($serverText -notmatch 'function\s+H\s*\(') 'ficha nao reutiliza o alias h do historico do PowerShell'
Assert-True ($serverText -match "\`$rota\s+-match\s+'\^/f/") 'servidor publica a ficha em uma rota curta e robusta'
Assert-True ($serverText -match 'text/html; charset=utf-8') 'ficha do QR e entregue como pagina HTML'
Assert-True ($serverText -notmatch '\$qrPayload\s*=\s*"http://\$qrHost') 'QR nao volta silenciosamente para endereco local'
Assert-True ($serverText -match 'QRCODE 382,188,M,5,A,0,M2,S7') 'TSPL imprime QR centralizado em modo automatico compativel'
Assert-True ($serverText -match 'QRCODE 402,174,M,4,A,0,M2,S7') 'TSPL reduz o QR quando existe observacao longa'
Assert-True ($serverText -match 'Wrap-TsplLines\s+-Text\s+\(\[string\]\$obs\)\.Trim\(\)\s+-MaxLen\s+69\s+-MaxLines\s+3') 'TSPL usa a largura completa para observacoes'
Assert-True ($serverText -match 'BAR 20,334,590,1') 'TSPL reserva faixa inferior completa para observacao com respiro visual'
Assert-True ($serverText -notmatch 'qrBinaryPayload|B\{0:D4\}') 'QR nao usa prefixo binario literal nem byte NUL'
Assert-True ($serverText -match "Get-Date\s+-Format\s+'dd/MM/yy'") 'data usa formato minimalista'
Assert-True ($serverText -match 'function\s+Confirm-VhsysOrdemServicoLocalizacao') 'servidor confirma localizacao geral apos cadastrar a OS'
Assert-True ($serverText -match 'id_almoxarifado\s*=\s*\$almoxarifadoBancadaTecnicaId') 'servidor envia TÉCNICA_BT como localizacao geral da OS'
Assert-True ($serverText -match 'Test-VhsysOrdemServicoLocalizacao') 'servidor valida a localizacao persistida pelo AlterTag'
Assert-True ($serverText -match 'foreach\s*\(\$tentativa\s+in\s+1\.\.2\)') 'confirmacao inicial de localizacao possui limite curto'
Assert-True ($serverText -match 'foreach\s*\(\$tentativaConsulta\s+in\s+1\.\.3\)') 'confirmacao do produto evita espera excessiva'
Assert-True ($serverText -match 'Get-VhsysProdutoCatalogoPorId\s+-Config\s+\$cfg\s+-IdProduto\s+\$IdProduto') 'servidor consulta preco atual antes de criar a OS'
Assert-True ($serverText -match '\$ProdutoValor\s*=\s*Normalize-VhsysValorUnitario') 'servidor substitui valor local pelo preco do AlterTag'
Assert-True ($serverText -notmatch '-SemLocalizacao') 'servidor nao permite fallback sem localizacao'
Assert-True ($serverText -notmatch 'tentando sem localizacao') 'servidor nao mascara falha da localizacao'
Assert-True ($serverText -notmatch 'throw\s+"A OS \$IdPedido foi criada, mas.*localizacao geral') 'localizacao nao confirmada nao abre alerta de erro no aplicativo'
Assert-True ($serverText -match 'Write-Host.*AlterTag nao confirmou a localizacao geral') 'servidor registra a falha de localizacao somente no diagnostico'
Assert-True ($serverText -match 'OS \$idPedido criada, mas o produto falhou') 'servidor registra pendencia sem negar criacao da OS'
Assert-True ($serverText -match 'produtoErro=\$out\.produtoErro') 'rota informa pendencia do produto'
Assert-True ($serverText -match 'function\s+New-CaijObservacaoCadastroOs') 'servidor formata observacao padronizada no cadastro'
Assert-True ($serverText -match "ToString\('dd/MM/yy'\)[\s\S]*?ToString\('HH:mm'\)") 'servidor usa prefixo com data e horario'
Assert-True ($serverText -match "ToString\('dd/MM/yy'\)") 'observacao da OS usa data curta'
Assert-True ($serverText -match "\`$obs\s+-match\s*'\^\\d\{2\}/\\d\{2\}/\\d\{2\}\\s\+-\\s\+\\d\{2\}:\\d\{2\}\\s\+-'") 'servidor reconhece observacao ja formatada no padrao curto'
Assert-True ($serverText -match '\$obs\s+-match ''\^\[A-Z\]\{3\}') 'servidor nao duplica observacao ja formatada'
Assert-True ($serverText -match 'New-VhsysOrdemServicoPayload[\s\S]*?-Observacao\s+\$observacaoFormatada') 'OS usa observacao formatada no payload'
Assert-True ($serverText -match '\$servOut\s*=\s*\[pscustomobject\]@\{[\s\S]*?servicos\s*=\s*@\(\)') 'cadastro nao envia itens para a aba servicos do Altertag'

'OK: InfoNotebookPreview tests'
